// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHutY3mNtD9q7BPvd4g3WH-Y4-kRYzZ_Y',
    appId: '1:438132186646:web:293dcd8fef02d6ca6e5f37',
    messagingSenderId: '438132186646',
    projectId: 'healthylife-bc3ee',
    authDomain: 'healthylife-bc3ee.firebaseapp.com',
    storageBucket: 'healthylife-bc3ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5n66mtUdom-vJzRDTqLpdIXAtKLL4yk',
    appId: '1:438132186646:android:9d9b7e13ef74a2796e5f37',
    messagingSenderId: '438132186646',
    projectId: 'healthylife-bc3ee',
    storageBucket: 'healthylife-bc3ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh1I6F1csmmwi7AMdydpqxCuMh6lO3pN8',
    appId: '1:438132186646:ios:2c8335af24bb09736e5f37',
    messagingSenderId: '438132186646',
    projectId: 'healthylife-bc3ee',
    storageBucket: 'healthylife-bc3ee.firebasestorage.app',
    iosBundleId: 'com.example.healthylife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh1I6F1csmmwi7AMdydpqxCuMh6lO3pN8',
    appId: '1:438132186646:ios:2c8335af24bb09736e5f37',
    messagingSenderId: '438132186646',
    projectId: 'healthylife-bc3ee',
    storageBucket: 'healthylife-bc3ee.firebasestorage.app',
    iosBundleId: 'com.example.healthylife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHutY3mNtD9q7BPvd4g3WH-Y4-kRYzZ_Y',
    appId: '1:438132186646:web:8a479fa1190db6466e5f37',
    messagingSenderId: '438132186646',
    projectId: 'healthylife-bc3ee',
    authDomain: 'healthylife-bc3ee.firebaseapp.com',
    storageBucket: 'healthylife-bc3ee.firebasestorage.app',
  );
}
